### ISSUE TITLE
Money Annotation doesn't work with bleeding edge symfony+doctrine

### ISSUE THREAD

**Issue by vvh-empora** [matmar10/money-bundle#2]
config.yml

```
matmar10_money:
    doctrine_connections:
        - "default"
```

entity:

``` PHP
/**
 * Description of OrderItem
 *
 * @ORM\Table(name="order_item")
 * @ORM\Entity()
 * @Matmar10\Bundle\MoneyBundle\Annotation\Entity()
 */
class OrderItem extends DBEntity {

    /**
     * @var Money
     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="price", currencyCode="currency", nullable=false)
     */
    private $price;

}

```

i get this error:

> Fatal error: Uncaught exception 'ReflectionException' with message 'Property OrderBundle\Entity\OrderItem::$currency does not exist' in /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 80

if i create matching properties in the given entity

``` PHP
    /**
     * @var int
     * @ORM\Column(name="price", type="integer", nullable=false)
     */
    private $priceAmount;

    /**
     * @var string
     * @ORM\Column(name="currency", type="string", length=3, nullable=false)
     */
    private $priceCurrency;

    /**
     * @var Money
     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="priceAmount", currencyCode="priceCurrency", nullable=false)
     */
    private $price;
```

i get this error:

> Fatal error: Uncaught exception 'Doctrine\ORM\Mapping\MappingException' with message 'Property "priceCurrency" in "OrderBundle\Entity\OrderItem" was already declared, but it must be declared only once' in /.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php on line 381

composer.json

> "doctrine/orm": "2.5._@dev",
> "doctrine/doctrine-bundle": "1.3._@dev",
> "matmar10/money-bundle": "dev-master",
> "matmar10/lib-money": "dev-master",

what can i do to fix this ? greez & thx!

**Comment by matmar10** [comment]
Try declaring properties as protected instead of private.

On Tuesday, May 26, 2015, vvh-empora notifications@github.com wrote:

> config.yml
> 
> matmar10_money:
>     doctrine_connections:
>         - "default"
> 
> entity:
> 
> /*\* \* Description of OrderItem \* \* @ORM\Table(name="order_item") \* @ORM\Entity() \* @Matmar10\Bundle\MoneyBundle\Annotation\Entity() _/class OrderItem extends DBEntity {    /_\*     \* @var Money     \* @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="price", currencyCode="currency", nullable=false)     */    private $price;}
> 
> i get this error:
> 
> Fatal error: Uncaught exception 'ReflectionException' with message
> 'Property Empora\FFX\OrderBundle\Entity\OrderItem::$currency does not
> exist' in
> /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php
> on line 80
> 
> if i create matching properties in the given entity
> 
> ```
> /**     * @var int     * @ORM\Column(name="price", type="integer", nullable=false)     */    private $priceAmount;    /**     * @var string     * @ORM\Column(name="currency", type="string", length=3, nullable=false)     */    private $priceCurrency;    /**     * @var Money     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="priceAmount", currencyCode="priceCurrency", nullable=false)     */    private $price;
> ```
> 
> i get this error:
> 
> Fatal error: Uncaught exception 'Doctrine\ORM\Mapping\MappingException'
> with message 'Property "priceCurrency" in
> "Empora\FFX\OrderBundle\Entity\OrderItem" was already declared, but it must
> be declared only once' in
> /var/www/dev/Fashionfreax-Platform/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php
> on line 381
> 
> composer.json
> 
> "doctrine/orm": "2.5.
> _@dev https://github.com/dev", "doctrine/doctrine-bundle": "1.3._@dev
> https://github.com/dev",
> "matmar10/money-bundle": "dev-master",
> "matmar10/lib-money": "dev-master",
> 
> what can i do to fix this ? greez & thx!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matmar10/money-bundle/issues/2.

## 

Matthew J. Martin
Founder, Blossom

https://blossomfinance.com

_Mobile USA: *+1 415 601 4879
*Mobile Indonesia: *+62 (0)812 9088 1641
*G+:_ Matthew.Mar10 | _Skype:_ MatMar10 | _Twitter:_ @ohbytheway
https://twitter.com/ohbytheway
_LinkedIn:_ https://www.linkedin.com/in/matthewjosephmartin

**Comment by matmar10** [comment]
Ah wait nevermind I see the issue. The problem is you are trying to use the
same property to hold both the money object and the integer amount.

Try changing the name of either the amountInteger property to something
like priceAmount.

On Tuesday, May 26, 2015, vvh-empora notifications@github.com wrote:

> config.yml
> 
> matmar10_money:
>     doctrine_connections:
>         - "default"
> 
> entity:
> 
> /*\* \* Description of OrderItem \* \* @ORM\Table(name="order_item") \* @ORM\Entity() \* @Matmar10\Bundle\MoneyBundle\Annotation\Entity() _/class OrderItem extends DBEntity {    /_\*     \* @var Money     \* @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="price", currencyCode="currency", nullable=false)     */    private $price;}
> 
> i get this error:
> 
> Fatal error: Uncaught exception 'ReflectionException' with message
> 'Property Empora\FFX\OrderBundle\Entity\OrderItem::$currency does not
> exist' in
> /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php
> on line 80
> 
> if i create matching properties in the given entity
> 
> ```
> /**     * @var int     * @ORM\Column(name="price", type="integer", nullable=false)     */    private $priceAmount;    /**     * @var string     * @ORM\Column(name="currency", type="string", length=3, nullable=false)     */    private $priceCurrency;    /**     * @var Money     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="priceAmount", currencyCode="priceCurrency", nullable=false)     */    private $price;
> ```
> 
> i get this error:
> 
> Fatal error: Uncaught exception 'Doctrine\ORM\Mapping\MappingException'
> with message 'Property "priceCurrency" in
> "Empora\FFX\OrderBundle\Entity\OrderItem" was already declared, but it must
> be declared only once' in
> /var/www/dev/Fashionfreax-Platform/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php
> on line 381
> 
> composer.json
> 
> "doctrine/orm": "2.5.
> _@dev https://github.com/dev", "doctrine/doctrine-bundle": "1.3._@dev
> https://github.com/dev",
> "matmar10/money-bundle": "dev-master",
> "matmar10/lib-money": "dev-master",
> 
> what can i do to fix this ? greez & thx!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matmar10/money-bundle/issues/2.

## 

Matthew J. Martin
Founder, Blossom

https://blossomfinance.com

_Mobile USA: *+1 415 601 4879
*Mobile Indonesia: *+62 (0)812 9088 1641
*G+:_ Matthew.Mar10 | _Skype:_ MatMar10 | _Twitter:_ @ohbytheway
https://twitter.com/ohbytheway
_LinkedIn:_ https://www.linkedin.com/in/matthewjosephmartin

**Comment by vvh-empora** [comment]
hmmm... same error ?

``` PHP
    /**
     * @var Money
     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="priceAmount", currencyCode="priceCurrency", nullable=false)
     */
    protected $price;
```

> Fatal error: Uncaught exception 'ReflectionException' with message 'Property OrderBundle\Entity\OrderItem::$priceCurrency does not exist' in /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 80

maybe some doctrine changes ?

**Comment by matmar10** [comment]
Hmm, could be - the bundle has not been updated to work with newer versions
of Symfony / Doctrine.

Can you provide a stack trace?

On Wednesday, May 27, 2015, vvh-empora notifications@github.com wrote:

> hmmm... same error ?
> 
> ```
> /**     * @var Money     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="priceAmount", currencyCode="priceCurrency", nullable=false)     */    protected $price;
> ```
> 
>  Fatal error: Uncaught exception 'ReflectionException' with message
> 'Property OrderBundle\Entity\OrderItem::$priceCurrency does not exist' in
> /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php
> on line 80
> 
> maybe some doctrine changes ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matmar10/money-bundle/issues/2#issuecomment-105802827
> .

## 

---

Matthew J. Martin

email: matthew.mar10@gmail.com
mobile: +1.415.601.4879
G+: Matthew.Mar10 | Skype: MatMar10

**Comment by vvh-empora** [comment]
> Symfony\Component\HttpKernel\Kernel->boot( )  ../FFXPlatformBootstrap.php:27
> AppKernel->initializeContainer( ) ../bootstrap.php.cache:2352
> Symfony\Component\HttpKernel\Kernel->initializeContainer( )   ../AppKernel.php:109
> Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp( ??? )  ../bootstrap.php.cache:2581
> Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp( ??? )   ../CacheWarmerAggregate.php:48
> Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata( )   ../ProxyCacheWarmer.php:69
> Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor( ??? )   ../AbstractClassMetadataFactory.php:115
> Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata( ??? )    ../AbstractClassMetadataFactory.php:216
> Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata( ??? ) ../ClassMetadataFactory.php:78
> Doctrine\ORM\Mapping\ClassMetadataFactory->wakeupReflection( ???, ??? )   ../AbstractClassMetadataFactory.php:343
> Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection( ??? )   ../ClassMetadataFactory.php:721
> Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty( ???, ??? )   ../ClassMetadataInfo.php:959
> __construct ( ???, ??? )  ../RuntimeReflectionService.php:80

or something like this:

> Uncaught exception 'ReflectionException' with message 'Property OrderBundle\Entity\OrderItem::$priceCurrencyCode does not exist' in /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80 Stack trace: #0 /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(80): ReflectionProperty->__construct('Empora\FFX\Orde...', 'priceCurrencyCo...') #1 /.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(959): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty('Empora\FFX\Orde...', 'priceCurrencyCo...') #2 /.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(721): Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection(Object(Doctrine\Common\Persistence\Mapping\RuntimeReflectionService)) #3 /.../vendor/do [file] => /.../vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php [line] => 80

**Comment by vvh-empora** [comment]
the main problem seems to be:

> .../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php::wakeupReflection()

this function will try to reference the given propertys from 

> .../vendor/matmar10/money-bundle/src/Matmar10/Bundle/MoneyBundle/Annotation/Money.php::getMap() [fieldName]

maybe we can fix it with the doctrine "embeddedClasses" functionality ?

**Comment by vvh-empora** [comment]
do you see any chance to get a fix in short time ?

**Comment by matmar10** [comment]
I tested with the following and was not able to reproduce this:
- doctrine/orm: v2.5.0
- symfony/symfony: v2.6.8

## Qualification Needed
- What version of Symfony are you using?
- What version does your composer.lock say are actually installed?
- Can you find what link your app is failing on inside `Matmar10\Bundle\MoneyBundle\Service\CompositePropertyService` ? If you can find which line is failing inside there it should be much easier to troubleshoot.

**Comment by matmar10** [comment]
Try removing the slash preceding the annotation: 
```
    /**
     * @var Money
     * @\Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="price", currencyCode="currency", nullable=false)
     */
    private $price;
```

```
    /**
     * @var Money
     * @Matmar10\Bundle\MoneyBundle\Annotation\Money(amountInteger="price", currencyCode="currency", nullable=false)
     */
    private $price;
```

**Comment by vvh-empora** [comment]
"symfony/symfony": "2.6.x-dev",

**Comment by vvh-empora** [comment]
removing the slash do not change anything... so i have already debug the code and all is running as aspected... but the given injected type from your lib will crash in my current doctrine version :(

**Comment by vvh-empora** [comment]
i think, the best solution is to use the DDD pattern from doctrine itself: http://docs.doctrine-project.org/en/latest/tutorials/embeddables.html

**Comment by matmar10** [comment]
Pull requests welcome :-)

**Comment by matmar10** [comment]
I tested with the following and could not reproduce this issue:

``` JavaScript
{
        "symfony/symfony": "^2.6",
        "symfony/framework-bundle": "~2.5.0",
        "doctrine/orm": "^2.5",
        "jms/serializer": "~0.15",
        "jms/aop-bundle": "~1.0",
        "matmar10/lib-money": "*"
    }
```

**Comment by vvh-empora** [comment]
try this one:

```
"symfony/symfony": "2.6.x-dev",
"doctrine/orm": "2.5.*@dev",
"doctrine/doctrine-bundle": "1.3.*@dev"
```

**Comment by matmar10** [comment]
Sorry, I don't have time to test against a non-production release (why are you using bleeding edge?). If there is a specific released version that's failing for you just let me know and I'm happy to test against that. 

Given that Doctrine now supports Embeddables, you may want to just create your own fork and re-work this module to use the Separating pattern, which didn't exist when I wrote this package originally. You could do something as simple as extend each lib-money class and annotate it with the Embeddables stuff. Then most of the code inside this package could be deprecated, except for the configuration related stuff for currency codes, etc... 

Good luck.

**Comment by leevigraham** [comment]
See: https://github.com/doctrine/doctrine2/issues/5663

**Comment by matmar10** [comment]
Hi @leevigraham unfortunately I'm no longer actively using/maintaining this library. Would you be interested in taking over ownership/maintenance? I am happy to hop on a call and help with it, but I won't be maintaining for future releases of Symfony/Doctrine.

**Comment by leevigraham** [comment]
@matmar10 sorry but I'm not in a position to maintain this library. I just threw the link in for others looking to solve the same issue.

**Comment by sharonLae** [comment]
Maybe it's because of doctrine cache, try clear it .
